export const IMAGE_COMMANDS = {
  uploadProfileImage: "image.uploadProfileImage",
  getProfileImage: "image.getProfileImage",
  uploadPostImage: "image.uploadPostImage",
  getPostImage: "image.getPostImage",
  deletePostImage: "image.deletePostImage",
  reorderPostImages: "image.reorderPostImages",
  createUserAlbum: "image.createUserAlbum",
  updateUserAlbum: "image.updateUserAlbum",
  deleteUserAlbum: "image.deleteUserAlbum",
  listUserPhotos: "image.listUserPhotos",
  uploadUserPhoto: "image.uploadUserPhoto",
  updateUserPhoto: "image.updateUserPhoto",
  deleteUserPhoto: "image.deleteUserPhoto",
  getUserPhoto: "image.getUserPhoto",
} as const;
